# Generated by Django 5.1.7 on 2025-03-16 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(error_messages={'incomplete': 'Enter a phone number.'}, max_length=24, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$', 'Enter a valid phone number.')])),
                ('courses', models.ManyToManyField(to='studentmanage.course')),
            ],
        ),
    ]
