# Generated by Django 5.1.7 on 2025-03-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='empty@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
