# Generated by Django 5.1.7 on 2025-03-18 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanage', '0004_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=datetime.datetime(2025, 3, 18, 9, 25, 53, 521104, tzinfo=datetime.timezone.utc), max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
