services:
  smsapp:
    container_name: smsapp
    # image: kallol7/smsapp:latest
    build: .
    env_file:
      - .env
    environment:
      # may need to change the value for local testing
      - SKEW_IN_SECONDS=0
    command: /bin/sh -c '
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn mysite.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - staticfiles:/usr/src/app/staticfiles
  nginx:
      image: nginx:stable
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/var/www/sms/staticfiles:ro
      ports:
        - "8080:80"
      depends_on:
        - smsapp
volumes:
  staticfiles: