global:
  scrape_interval: 1m
  evaluation_interval: 1m 
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    static_configs: 
      - targets: ["host.docker.internal:8080"]
      - labels:
          app: smsapp
